Добавить класс JSExecutor.java для JavascriptExecutor
meridian285/way_automation pull request #3
Opened 2023-06-08 11:18 UTC by meridian285

Добавить тест на проверку скроллбаров DummyRegistrationFormTests.testScroll

2023-06-09 11:22 UTC, nazarovvi requested changes

2023-06-09 11:22 UTC, nazarovvi commented on src/test/java/com/way2automation/help/JSExecutor.java
> +        ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", webElement);
`((JavascriptExecutor) driver)` почему бы не вынести это в отдельное поле в классе, чтобы не приводить типы каждый раз?

2023-06-09 11:22 UTC, nazarovvi commented on src/test/java/com/way2automation/help/JSExecutor.java
> +public class JSExecutor {
Нарущение camelCase

2023-06-09 11:22 UTC, nazarovvi commented on src/test/java/com/way2automation/tests/DummyRegistrationFormTests.java
> +        Assert.assertTrue(new JSExecutor(driver).testVertScrollStatus(), "Проверка на вертикальную полосу прокрутки");
Каши навертел. Убери методы в пэйджКласс, к которму они относятся. 
Ещё лучше было бы и ассерты убрать внутрь пэйджей, чтобы тесты выглядели чище

2023-06-13 16:15 UTC, meridian285 commented on src/test/java/com/way2automation/tests/DummyRegistrationFormTests.java
> +        Assert.assertTrue(new JSExecutor(driver).testVertScrollStatus(), "Проверка на вертикальную полосу прокрутки");
ктото просит выводить проверки, если есть возможность, в тесты, ктото прятать....

2023-06-19 09:39 UTC, nazarovvi commented on src/test/java/com/way2automation/tests/DummyRegistrationFormTests.java
> +        Assert.assertTrue(new JSExecutor(driver).testVertScrollStatus(), "Проверка на вертикальную полосу прокрутки");
Тут суть в чем, проверка в тесте должна быть обязательно, но при это голый ассерт в тесте оставлять не обязательно. Добавляешь метод чекЧтоТоТам, и всё, тест читается, из названия метода сразу понятно, что мы проверяем, всё выглядит лаконично

2023-06-20 12:10 UTC, meridian285 commented on src/test/java/com/way2automation/tests/DummyRegistrationFormTests.java
> +        Assert.assertTrue(new JSExecutor(driver).testVertScrollStatus(), "Проверка на вертикальную полосу прокрутки");
Я согласен (мне тоже нравится когда проверки в page классе), но даже на практике от вашей компании меня поправляли и просили вытащить именно ассерты в тестовые методы. Поэтому я и делаю так

2023-06-27 18:03 UTC, nazarovvi commented
Можно мержить

2023-06-29 05:13 UTC, merged